name: Release

on:
  push:
    paths:
      - '.github/workflows/release.yml'
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'index.js'

env:
  VERSION: 2026.3.23-2

jobs:
  release-docker:
    runs-on: ubuntu-latest
    if: ${{ vars.DOCKER_REGISTRY != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Docker
        uses: seepine/action-setup-docker@v1
        id: meta
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/openclaw:${{ env.VERSION }}
            ${{ vars.DOCKER_USERNAME }}/openclaw:latest

      - name: Success
        run: echo "Release ${{ env.VERSION }} success"

  release-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Docker
        uses: seepine/action-setup-docker@v1
        id: meta
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/openclaw:${{ env.VERSION }}
            ghcr.io/${{ github.actor }}/openclaw:latest

      - name: Success
        run: echo "Release ${{ env.VERSION }} success"
